### ISSUE TITLE
About your glove embeddings

### ISSUE THREAD

**Issue by ybCliff** [WingsBrokenAngel/delving-deeper-into-the-decoder-for-video-captioning#1]
非常感谢您的分享，想请问一下：
1）glove词向量是如何提取到的呢，有链接么？
2）bos eos pad unk 我看到都有对应的词向量，是如何做到的呢？

**Comment by WingsBrokenAngel** [comment]
1) 来自斯坦福的glove 840B 300d[预训练词嵌入](https://nlp.stanford.edu/projects/glove/)。
2) 都是随机出来的
