### ISSUE TITLE
测试所用数据的生成代码

### ISSUE THREAD

**Issue by Mintcat10** [WingsBrokenAngel/delving-deeper-into-the-decoder-for-video-captioning#2]
你好,可以提供下面四个文件的生成代码吗?
```
    --corpus ./msvd_feats/msvd_corpus_glove.pkl \
    --ecores ./msvd_feats/msvd_eco_norm.npy \
    --tag    ./msvd_feats/msvd_semantic_tag_res_avg.npy \
    --ref    ./msvd_feats/msvd_ref3.pkl \
```
另外MSR-VTT的测试数据可以用同样的方式生成吗?

**Comment by WingsBrokenAngel** [comment]
请参考这个issue：https://github.com/WingsBrokenAngel/Semantics-AssistedVideoCaptioning/issues/2和代码库https://github.com/WingsBrokenAngel/Semantics-AssistedVideoCaptioning。

上面这个工作和本工作是紧密联系的，相当一部分文件是复用的。

我只能告诉你是怎么生成这些文件。由于这些操作大多都是在命令行上完成，除了语义信息的生成，其他没有代码文件。

**Comment by Mintcat10** [comment]
多谢.
