### ISSUE TITLE
run file missing

### ISSUE THREAD

**Issue by Mollylulu** [WingsBrokenAngel/delving-deeper-into-the-decoder-for-video-captioning#3]
Hi, I do not find the run_model.sh file in this repo. Where is it? Thanks in advance.

**Comment by WingsBrokenAngel** [comment]
You may find it in msrvtt folder or msvd folder.

**Comment by Mollylulu** [comment]
> You may find it in msrvtt folder or msvd folder.

I see it. :) Thx
