### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Mollylulu** [WingsBrokenAngel/delving-deeper-into-the-decoder-for-video-captioning#4]
What is wrong with it? I just download the msr-vtt data files and the checkpoint.

![1](https://user-images.githubusercontent.com/26273127/86574424-68b00b00-bfa8-11ea-959c-9ab9921029c3.png)

**Comment by WingsBrokenAngel** [comment]
Pls make sure you have downloaded the data files successfully.

**Comment by Mollylulu** [comment]
> Pls make sure you have downloaded the data files successfully.

After I reconnect the colab, it works. :sweat_smile:
