### ISSUE TITLE
Inference on single video

### ISSUE THREAD

**Issue by nikky4D** [WingsBrokenAngel/delving-deeper-into-the-decoder-for-video-captioning#5]
Hi, 

do you have a demo.py/ipynb that I can use to run inference on a single video to see the captions generated? If not, can you describe how I can go about making this setup? 

Thanks

**Comment by WingsBrokenAngel** [comment]
1. Encoder part: use ResNeXt, ECO and Semantic Detection Network to extract features from a video clip.
2. Decoder part: use those features as inputs to the captioning model.

**Comment by amil-rp-work** [comment]
@WingsBrokenAngel 
Can you please provide code/repo links on how to go about feature extraction for encoder part?

**Comment by WingsBrokenAngel** [comment]
> @WingsBrokenAngel
> Can you please provide code/repo links on how to go about feature extraction for encoder part?

ResNeXt could be found in [tensornets](https://github.com/taehoonlee/tensornets) and ECO could be found in [ECO-efficient-video-understanding](https://github.com/mzolfaghari/ECO-efficient-video-understanding).
